analyzer:
  errors:
    no_wildcard_variable_uses: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - windows/**
include: package:lints/recommended.yaml

linter:
  rules:
    constant_identifier_names: false
    prefer_const_constructors: true
