targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - pubspec.yaml
      - lib/models/api_v2/**
      - lib/models/api_v2/swagger/**
      - lib/utils/env/**
    builders:
      envied_generator|envied:
        options:
          path: .env
          override: true
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "lib/models/api_v2/swagger/"
          output_folder: "lib/models/api_v2/"
          type_mappings:
            "ForumId": "int"
